<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Communication.Email" Version="1.1.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.19.1" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="FirebaseAdmin" Version="3.6.0" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.22" />
    <PackageReference Include="Hangfire.Core" Version="1.8.22" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.8.22" />
    <PackageReference Include="MailKit" Version="4.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.0" />
	  <PackageReference Include="Serilog.Enrichers.Process" Version="2.0.2" />
	  <PackageReference Include="Serilog.Enrichers.Thread" Version="3.1.0" />
	  <PackageReference Include="Serilog.Expressions" Version="4.0.0" />
	  <PackageReference Include="Serilog.Enrichers.Environment" Version="2.3.0" />
	  <PackageReference Include="Serilog.Formatting.Compact" Version="2.0.0" />
	  <PackageReference Include="Serilog.Sinks.Async" Version="1.5.0" />
	  <PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
	  <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
	  <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="6.5.0" />
	  <PackageReference Include="Serilog.Sinks.Elasticsearch" Version="10.0.0" />
	  <PackageReference Include="Serilog.Sinks.Seq" Version="6.0.0" />
	  <PackageReference Include="Serilog.Exceptions" Version="8.4.0" />
	  <PackageReference Include="Smtp2Go.ApiClient" Version="0.0.5" />
	  <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
	  <PackageReference Include="Microsoft.Graph" Version="4.54.0" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\" />
  </ItemGroup>

</Project>
